name: PR 15-Min Build Pass Job

on:
  pull_request:
    branches:
      - main  # or your default target branch
    types: [opened, synchronize, reopened]

jobs:
  run-if-branch-has-build:
    if: contains(github.head_ref, 'build')
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 15 minutes
        run: sleep 900  # 900 seconds = 15 minutes

      - name: Done
        run: echo "✅ Job passed after 15 minutes on branch '${{ github.head_ref }}'"
