name: PR 5-Min Pass Job for 'pass' Branches

on:
  pull_request:
    branches:
      - main  # or your default branch
    types: [opened, synchronize, reopened]

jobs:
  run-if-branch-has-pass:
    if: contains(github.head_ref, 'pass')
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 minutes
        run: sleep 300

      - name: Done
        run: echo "✅ Passed after 5 minutes for branch '${{ github.head_ref }}'"
